FROM adaickalavan/gocvkafka-alpine as buildstage

# Enable GO111MODULE
ENV GO111MODULE=on

# Author label
LABEL Author Adaickalavan Meiyappan

# Set the working directory outside $GOPATH to enable the support for modules.
WORKDIR /src

# Fetch dependencies first; they are less susceptible to change on every build
# and will therefore be cached for speeding up the next build
COPY ./go.mod ./go.sum ./
RUN export HTTP_PROXY=http://10.77.8.70:8080/ \
    && export HTTPS_PROXY=http://10.77.8.70:8080/ \ 
    && go mod download \
    && unset HTTP_PROXY \
    && unset HTTPS_PROXY

# Copy the local package files (from development computer) to the container's workspace (docker image)
COPY . .

# Build the executable to `/app`. Mark the build as statically linked.
RUN go build -o /app .

# Run the compiled binary when the conainer starts
ENTRYPOINT ["/app"]