apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: govideo
  annotations:
      contact: adaickalavan <adaickalavan@gmail.com> 

spec:
  replicas: 1
  
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1

  selector:
    matchLabels:
      app: govideo

  template:
    metadata:
      name: govideo
      labels:
        app: govideo
    spec:
      containers:
        - name: govideo
          image: govideo
          imagePullPolicy: IfNotPresent
          env:
            - name: TOPICNAME
              value: videodisplay
            - name: KAFKAPORT
              value: kf1-service:19095
            - name: GROUPNAME
              value: govideo
            - name: DISPLAYPORT
              value: :8080  
            - name: NODEPORT
              value: :30163  
            - name: FRAMEINTERVAL
              value: "42ms"     
          resources:

---
kind: Service
apiVersion: v1
metadata:
  name: govideo-service
  namespace: default

spec:
  type: NodePort

  selector:
    app: govideo

  ports:
    # Three types of ports for a service
    # nodePort - a static port assigned on each the node
    # port     - port exposed internally in the cluster
    # targetPort - the container port to send requests to
    - name: govideo-port
      nodePort: 30163 
      port: 8080
